# Generated by Django 2.1 on 2019-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
