# Generated by Django 2.1 on 2019-11-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191119_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='name',
            new_name='title',
        ),
    ]
