# Generated by Django 2.1 on 2019-12-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
